/* ===== 環境音：全部以 WebAudio 合成（無外部音檔）。鳥叫、風與樹葉、蟬鳴、車流、咖啡廳、腳步 ===== */
'use strict';
const A3 = (function(){
  const A={ctx:null,master:null,vol:0.6,scene:null,layers:{},started:false};
  function ctx(){ if(!A.ctx){ const C=window.AudioContext||window.webkitAudioContext; if(!C) return null; A.ctx=new C(); A.master=A.ctx.createGain(); A.master.gain.value=A.vol; A.master.connect(A.ctx.destination); } return A.ctx; }
  A.start=function(){ const c=ctx(); if(!c) return; if(c.state==='suspended') c.resume(); A.started=true; };
  A.setVolume=function(v){ A.vol=v; if(A.master) A.master.gain.setTargetAtTime(v,A.ctx.currentTime,0.05); };
  function noiseBuf(c,sec){ const n=c.sampleRate*sec; const b=c.createBuffer(1,n,c.sampleRate); const d=b.getChannelData(0); let last=0; for(let i=0;i<n;i++){ const w=Math.random()*2-1; last=(last+0.02*w)/1.02; d[i]=last*3.5; } return b; }
  function layer(name,make){ if(A.layers[name]) return A.layers[name]; const c=ctx(); if(!c) return null; const g=c.createGain(); g.gain.value=0; g.connect(A.master); const l={g,stop:make(c,g)}; A.layers[name]=l; return l; }
  // 風與樹葉：粉紅噪音 + 慢 LFO
  function mkWind(c,g){ const src=c.createBufferSource(); src.buffer=noiseBuf(c,4); src.loop=true; const f=c.createBiquadFilter(); f.type='bandpass'; f.frequency.value=900; f.Q.value=0.6; const lfo=c.createOscillator(); lfo.frequency.value=0.13; const lg=c.createGain(); lg.gain.value=350; lfo.connect(lg); lg.connect(f.frequency); const lfo2=c.createOscillator(); lfo2.frequency.value=0.07; const ag=c.createGain(); ag.gain.value=0.5; const amp=c.createGain(); amp.gain.value=0.6; lfo2.connect(ag); ag.connect(amp.gain); src.connect(f); f.connect(amp); amp.connect(g); src.start(); lfo.start(); lfo2.start(); return ()=>{ src.stop(); lfo.stop(); lfo2.stop(); }; }
  // 鳥叫：隨機短促的頻率滑音
  function mkBirds(c,g){ let alive=true; const tick=()=>{ if(!alive) return; if(Math.random()<0.7){ const n=1+(Math.random()*3|0); for(let i=0;i<n;i++){ const t=c.currentTime+i*0.16+Math.random()*0.05; const o=c.createOscillator(); o.type='sine'; const f0=2200+Math.random()*1800; o.frequency.setValueAtTime(f0,t); o.frequency.exponentialRampToValueAtTime(f0*(1.2+Math.random()*0.5),t+0.06); o.frequency.exponentialRampToValueAtTime(f0*0.8,t+0.14); const e=c.createGain(); e.gain.setValueAtTime(0,t); e.gain.linearRampToValueAtTime(0.09,t+0.02); e.gain.exponentialRampToValueAtTime(0.001,t+0.16); const pan=c.createStereoPanner?c.createStereoPanner():null; if(pan){ pan.pan.value=Math.random()*2-1; o.connect(e); e.connect(pan); pan.connect(g); } else { o.connect(e); e.connect(g); } o.start(t); o.stop(t+0.2); } } setTimeout(tick,1500+Math.random()*4000); }; tick(); return ()=>{ alive=false; }; }
  // 蟬鳴：高頻調幅噪音
  function mkCicada(c,g){ const src=c.createBufferSource(); src.buffer=noiseBuf(c,3); src.loop=true; const f=c.createBiquadFilter(); f.type='bandpass'; f.frequency.value=5200; f.Q.value=6; const am=c.createOscillator(); am.frequency.value=38; const amg=c.createGain(); amg.gain.value=0.5; const amp=c.createGain(); amp.gain.value=0.5; am.connect(amg); amg.connect(amp.gain); const lfo=c.createOscillator(); lfo.frequency.value=0.09; const lg=c.createGain(); lg.gain.value=0.35; lfo.connect(lg); lg.connect(amp.gain); src.connect(f); f.connect(amp); amp.connect(g); src.start(); am.start(); lfo.start(); return ()=>{ src.stop(); am.start&&am.stop(); lfo.stop(); }; }
  // 車流：低頻噪音 + 偶爾經過的機車
  function mkTraffic(c,g){ const src=c.createBufferSource(); src.buffer=noiseBuf(c,4); src.loop=true; const f=c.createBiquadFilter(); f.type='lowpass'; f.frequency.value=320; const amp=c.createGain(); amp.gain.value=1.4; src.connect(f); f.connect(amp); amp.connect(g); src.start(); let alive=true; const pass=()=>{ if(!alive) return; const t=c.currentTime; const o=c.createOscillator(); o.type='sawtooth'; o.frequency.setValueAtTime(90,t); o.frequency.linearRampToValueAtTime(160,t+1.2); o.frequency.linearRampToValueAtTime(70,t+2.6); const lf=c.createBiquadFilter(); lf.type='lowpass'; lf.frequency.value=500; const e=c.createGain(); e.gain.setValueAtTime(0,t); e.gain.linearRampToValueAtTime(0.05,t+1.2); e.gain.linearRampToValueAtTime(0,t+2.8); const pan=c.createStereoPanner?c.createStereoPanner():null; if(pan){ pan.pan.setValueAtTime(-1,t); pan.pan.linearRampToValueAtTime(1,t+2.8); o.connect(lf); lf.connect(e); e.connect(pan); pan.connect(g); } else { o.connect(lf); lf.connect(e); e.connect(g); } o.start(t); o.stop(t+3); setTimeout(pass,4000+Math.random()*9000); }; setTimeout(pass,2000); return ()=>{ alive=false; src.stop(); }; }
  // 室內：輕微空調嗡聲 + 咖啡廳偶爾杯盤聲
  function mkRoom(c,g,cafe){ const src=c.createBufferSource(); src.buffer=noiseBuf(c,3); src.loop=true; const f=c.createBiquadFilter(); f.type='lowpass'; f.frequency.value=220; const amp=c.createGain(); amp.gain.value=0.7; src.connect(f); f.connect(amp); amp.connect(g); src.start(); let alive=true; if(cafe){ const clink=()=>{ if(!alive) return; const t=c.currentTime; const o=c.createOscillator(); o.type='triangle'; o.frequency.value=2600+Math.random()*1500; const e=c.createGain(); e.gain.setValueAtTime(0.03,t); e.gain.exponentialRampToValueAtTime(0.0005,t+0.25); o.connect(e); e.connect(g); o.start(t); o.stop(t+0.3); setTimeout(clink,5000+Math.random()*12000); }; setTimeout(clink,3000); } return ()=>{ alive=false; src.stop(); }; }
  const DEFS={wind:mkWind,birds:mkBirds,cicada:mkCicada,traffic:mkTraffic,room:(c,g)=>mkRoom(c,g,false),cafe:(c,g)=>mkRoom(c,g,true)};
  // 目標音量表：依區域與時間
  A.setScene=function(zoneId,hour,weather){ if(!A.ctx) return; const h=hour%24; const day=h>6&&h<19; const dusk=h>=16.5&&h<19.5; const t={wind:0,birds:0,cicada:0,traffic:0,room:0,cafe:0};
    if(zoneId==='campus'){ t.wind=weather==='rain'?0.35:0.22; t.birds=day?(dusk?0.35:0.6):0.05; t.cicada=dusk?0.28:(day?0.1:0.0); t.traffic=0.06; }
    else if(zoneId==='gongguan'){ t.traffic=0.5; t.wind=0.08; t.birds=day?0.08:0; }
    else if(zoneId==='wenzhou'){ t.traffic=0.16; t.wind=0.14; t.birds=day?0.25:0.02; t.cicada=dusk?0.18:0; }
    else if(zoneId==='cafe'){ t.cafe=0.5; t.traffic=0.04; }
    else { t.room=0.5; t.traffic=zoneId==='cvs'||zoneId==='noodle'?0.1:0.03; }
    for(const k in t){ const l=layer(k,DEFS[k]); if(!l) continue; l.g.gain.setTargetAtTime(t[k],A.ctx.currentTime,1.2); } };
  // 腳步：短噪音爆
  A.step=function(run,indoor){ const c=A.ctx; if(!c||!A.started) return; const t=c.currentTime; const src=c.createBufferSource(); const n=c.sampleRate*0.07; const b=c.createBuffer(1,n,c.sampleRate); const d=b.getChannelData(0); for(let i=0;i<n;i++){ d[i]=(Math.random()*2-1)*Math.pow(1-i/n,2.5); } src.buffer=b; const f=c.createBiquadFilter(); f.type=indoor?'lowpass':'bandpass'; f.frequency.value=indoor?900:1500; const e=c.createGain(); e.gain.value=(run?0.16:0.09); src.connect(f); f.connect(e); e.connect(A.master); src.start(t); };
  // 小音效：確認、翻頁、鐘聲
  A.blip=function(kind){ const c=A.ctx; if(!c||!A.started) return; const t=c.currentTime; const o=c.createOscillator(); const e=c.createGain(); o.connect(e); e.connect(A.master); if(kind==='bell'){ o.type='sine'; o.frequency.value=660; e.gain.setValueAtTime(0.18,t); e.gain.exponentialRampToValueAtTime(0.001,t+2.2); const o2=c.createOscillator(); o2.type='sine'; o2.frequency.value=1320; const e2=c.createGain(); e2.gain.setValueAtTime(0.06,t); e2.gain.exponentialRampToValueAtTime(0.001,t+1.5); o2.connect(e2); e2.connect(A.master); o2.start(t); o2.stop(t+2.3); o.start(t); o.stop(t+2.3); return; } o.type='triangle'; o.frequency.value=kind==='ok'?880:(kind==='page'?520:660); e.gain.setValueAtTime(0.06,t); e.gain.exponentialRampToValueAtTime(0.001,t+0.12); o.start(t); o.stop(t+0.14); };
  return A;
})();
