/* ===== 人物層（CHARACTER LAYER）
   gameplay / engine 只呼叫 CHAR.build / CHAR.animate / CHAR.setExpr / CHAR.headY。
   driver 'glb'：rigged GLB（Mixamo 相容骨架，例如 Ready Player Me）＋ Mixamo 動畫（rest-pose 補償重定向）
   driver 'proc'：P3 程序化人物（PLACEHOLDER_CHARACTER） ===== */
'use strict';
const CHAR = (function(){
  const C={};
  const POSE_CLIP={idle:'idle',walk:'walk',run:'run',talk:'idle',wave:'idle',sit:null,read:null};
  // ---- 重定向：以兩個骨架的 rest pose 世界旋轉補償 bind pose 差異（來源：Mixamo 命名 mixamorigX → 目標 X）----
  function restMap(root){ root.updateMatrixWorld(true); const m=new Map(); root.traverse(o=>{ const wq=new THREE.Quaternion(); o.getWorldQuaternion(wq); m.set(o.name,{wq,node:o}); }); return m; }
  C.retargetClipSimple=function(clip,srcRoot,dstRoot,opts){ opts=opts||{}; const S=restMap(srcRoot), D=restMap(dstRoot); const tracks=[]; const tmpQ=new THREE.Quaternion(), q=new THREE.Quaternion();
    for(const t of clip.tracks){ const m=t.name.match(/^(.+)\.(quaternion|position)$/); if(!m) continue; const srcName=m[1]; const dstName=srcName.replace(/^mixamorig:?/,''); const s=S.get(srcName), d=D.get(dstName); if(!s||!d) continue;
      if(m[2]==='position'){ if(dstName!=='Hips') continue; const sp=s.node.position, dp=d.node.position; const sc=opts.posScale||1; const vals=new Float32Array(t.values.length); for(let i=0;i<t.times.length;i++){ vals[i*3]=dp.x; vals[i*3+1]=dp.y+(t.values[i*3+1]-sp.y)*sc; vals[i*3+2]=dp.z; } tracks.push(new THREE.VectorKeyframeTrack(dstName+'.position',Array.from(t.times),Array.from(vals))); continue; }
      const spW=new THREE.Quaternion(); if(s.node.parent) s.node.parent.getWorldQuaternion(spW); const dpW=new THREE.Quaternion(); if(d.node.parent) d.node.parent.getWorldQuaternion(dpW); const sInv=s.wq.clone().invert(); const dpInv=dpW.clone().invert();
      const vals=new Float32Array(t.values.length); for(let i=0;i<t.times.length;i++){ q.set(t.values[i*4],t.values[i*4+1],t.values[i*4+2],t.values[i*4+3]); tmpQ.copy(spW).multiply(q).multiply(sInv); tmpQ.premultiply(dpInv).multiply(d.wq); vals[i*4]=tmpQ.x; vals[i*4+1]=tmpQ.y; vals[i*4+2]=tmpQ.z; vals[i*4+3]=tmpQ.w; }
      tracks.push(new THREE.QuaternionKeyframeTrack(dstName+'.quaternion',Array.from(t.times),Array.from(vals))); }
    return new THREE.AnimationClip(clip.name,clip.duration,tracks); };
  /* 重定向 v2：來源（Mixamo，T-pose、骨頭沿 +X）→ 目標（例如 Ready Player Me，A-pose、骨頭沿 +Y）。
     方法：每個 frame 沿階層計算來源骨頭的世界旋轉，乘上每根骨頭固定的補償 C = inv(Bs) · A · Bd，
     其中 Bs/Bd 是兩邊的 rest 世界旋轉，A 是把目標 rest 骨頭方向轉到來源 rest 骨頭方向的最小旋轉（消除 T-pose／A-pose 差異與軸向慣例差異），
     再用目標父骨頭「動畫中」的世界旋轉換回 local。Hips 位置 = 目標 rest 位置 + 來源位移 × posScale。 */
  const CHAIN_CHILD={Hips:'Spine',Spine:'Spine1',Spine1:'Spine2',Spine2:'Neck',Neck:'Head',Head:'HeadTop_End',LeftShoulder:'LeftArm',LeftArm:'LeftForeArm',LeftForeArm:'LeftHand',LeftHand:'LeftHandMiddle1',RightShoulder:'RightArm',RightArm:'RightForeArm',RightForeArm:'RightHand',RightHand:'RightHandMiddle1',LeftUpLeg:'LeftLeg',LeftLeg:'LeftFoot',LeftFoot:'LeftToeBase',LeftToeBase:'LeftToe_End',RightUpLeg:'RightLeg',RightLeg:'RightFoot',RightFoot:'RightToeBase',RightToeBase:'RightToe_End'};
  function sampleQuat(track,t,out){ const T=track.times, V=track.values; const n=T.length; if(t<=T[0]){ out.fromArray(V,0); return out; } if(t>=T[n-1]){ out.fromArray(V,(n-1)*4); return out; } let lo=0, hi=n-1; while(hi-lo>1){ const mid=(lo+hi)>>1; if(T[mid]<=t) lo=mid; else hi=mid; } const a=new THREE.Quaternion().fromArray(V,lo*4), b=new THREE.Quaternion().fromArray(V,hi*4); const f=(t-T[lo])/Math.max(1e-6,T[hi]-T[lo]); out.copy(a).slerp(b,f); return out; }
  function sampleVec(track,t,out){ const T=track.times, V=track.values; const n=T.length; if(t<=T[0]){ out.fromArray(V,0); return out; } if(t>=T[n-1]){ out.fromArray(V,(n-1)*3); return out; } let lo=0, hi=n-1; while(hi-lo>1){ const mid=(lo+hi)>>1; if(T[mid]<=t) lo=mid; else hi=mid; } const a=new THREE.Vector3().fromArray(V,lo*3), b=new THREE.Vector3().fromArray(V,hi*3); const f=(t-T[lo])/Math.max(1e-6,T[hi]-T[lo]); out.copy(a).lerp(b,f); return out; }
  C.retargetClip=function(clip,srcRoot,dstRoot,opts){ opts=opts||{}; const fps=opts.fps||30; const prefix=/^mixamorig:?/;
    srcRoot.updateMatrixWorld(true); dstRoot.updateMatrixWorld(true);
    // 來源／目標骨頭表（rest 世界旋轉、位置）
    const src={}, dst={}; srcRoot.traverse(o=>{ if(prefix.test(o.name)) src[o.name.replace(prefix,'')]=o; }); dstRoot.traverse(o=>{ if(o.isBone||src[o.name]) if(src[o.name]||o.isBone) dst[o.name]=o; });
    const wq=o=>{ const q=new THREE.Quaternion(); o.getWorldQuaternion(q); return q; }; const wp=o=>{ const v=new THREE.Vector3(); o.getWorldPosition(v); return v; };
    const Bs={}, Bd={}, Ps={}, Pd={}; for(const n in src){ Bs[n]=wq(src[n]); Ps[n]=wp(src[n]); } for(const n in dst){ Bd[n]=wq(dst[n]); Pd[n]=wp(dst[n]); }
    // 補償 C
    const Cq={}; for(const n in dst){ if(!src[n]) continue; const cn=CHAIN_CHILD[n]; let A=new THREE.Quaternion(); if(cn&&src[cn]&&dst[cn]){ const ds=Ps[cn].clone().sub(Ps[n]).normalize(), dd=Pd[cn].clone().sub(Pd[n]).normalize(); if(ds.lengthSq()>0.5&&dd.lengthSq()>0.5) A.setFromUnitVectors(dd,ds); } Cq[n]=Bs[n].clone().invert().multiply(A).multiply(Bd[n]); }
    // 來源軌道
    const qTracks={}, pTracks={}; for(const t of clip.tracks){ const m=t.name.match(/^(.+)\.(quaternion|position)$/); if(!m) continue; const n=m[1].replace(prefix,''); if(m[2]==='quaternion') qTracks[n]=t; else pTracks[n]=t; }
    // 階層順序（父在前）
    const order=[]; dstRoot.traverse(o=>{ if(dst[o.name]) order.push(o.name); });
    const nF=Math.max(2,Math.round(clip.duration*fps)+1); const times=new Float32Array(nF); const outQ={}; for(const n of order) if(src[n]) outQ[n]=new Float32Array(nF*4);
    const hipsPos=(pTracks.Hips&&dst.Hips)?new Float32Array(nF*3):null; const sc=opts.posScale||1; const srcHipRest=src.Hips?src.Hips.position.clone():new THREE.Vector3(); const dstHipRest=dst.Hips?dst.Hips.position.clone():new THREE.Vector3();
    const Ws={}, Wd={}; const q=new THREE.Quaternion(), v=new THREE.Vector3();
    for(let i=0;i<nF;i++){ const t=Math.min(clip.duration,i/fps); times[i]=t;
      // 來源世界旋轉（沿階層）
      srcRoot.traverse(o=>{ if(!prefix.test(o.name)) return; const n=o.name.replace(prefix,''); const tr=qTracks[n]; const lq=tr?sampleQuat(tr,t,q).clone():o.quaternion.clone(); const par=o.parent; const pn=par&&prefix.test(par.name)?par.name.replace(prefix,''):null; const pw=pn&&Ws[pn]?Ws[pn]:(par?wq(par):new THREE.Quaternion()); Ws[n]=pw.clone().multiply(lq); });
      for(const n of order){ const o=dst[n]; const par=o.parent; const pn=par&&dst[par.name]?par.name:null; const pw=pn&&Wd[pn]?Wd[pn]:(par?wq(par):new THREE.Quaternion());
        let w; if(src[n]&&Ws[n]) w=Ws[n].clone().multiply(Cq[n]); else w=pw.clone().multiply(o.quaternion); Wd[n]=w;
        if(outQ[n]){ const lq=pw.clone().invert().multiply(w); outQ[n][i*4]=lq.x; outQ[n][i*4+1]=lq.y; outQ[n][i*4+2]=lq.z; outQ[n][i*4+3]=lq.w; } }
      if(hipsPos){ sampleVec(pTracks.Hips,t,v); hipsPos[i*3]=dstHipRest.x+(v.x-srcHipRest.x)*sc*(opts.hipXZ?1:0); hipsPos[i*3+1]=dstHipRest.y+(v.y-srcHipRest.y)*sc; hipsPos[i*3+2]=dstHipRest.z+(v.z-srcHipRest.z)*sc*(opts.hipXZ?1:0); } }
    const tracks=[]; for(const n in outQ) tracks.push(new THREE.QuaternionKeyframeTrack(n+'.quaternion',Array.from(times),Array.from(outQ[n]))); if(hipsPos) tracks.push(new THREE.VectorKeyframeTrack('Hips.position',Array.from(times),Array.from(hipsPos)));
    return new THREE.AnimationClip(clip.name,clip.duration,tracks); };
  // 每個人物模板只重定向一次
  function clipsFor(modelKey){ if(ASSETS.clips[modelKey]) return ASSETS.clips[modelKey]; const m=ASSETS.manifest[modelKey]; const tpl=ASSETS.getRaw(modelKey); const src=ASSETS.getRaw(m.anims); if(!tpl||!src) return null; let hips=null; src.scene.traverse(o=>{ if(/Hips$/.test(o.name)&&!hips) hips=o; }); const sc=hips?hips.parent.getWorldScale(new THREE.Vector3()).y:1; const out={}; for(const a of src.animations){ out[a.name]=C.retargetClip(a,src.scene,tpl.scene,{posScale:sc}); } ASSETS.clips[modelKey]=out; return out; }
  C.canGLB=function(spec){ return !!(spec&&spec.model&&ASSETS.has(spec.model)&&ASSETS.manifest[spec.model].type!=='vrm'&&ASSETS.has(ASSETS.manifest[spec.model].anims)); };
  C.useModels=true;
  C.canVRM=function(spec){ return !!(C.useModels!==false&&spec&&spec.model&&typeof THREE_VRM!=='undefined'&&ASSETS.has(spec.model)&&ASSETS.manifest[spec.model].type==='vrm'&&ASSETS.has(ASSETS.manifest[spec.model].anims)&&ASSETS.vrmFree(spec.model)>0); };
  /* ---- VRM driver（@pixiv/three-vrm；VRM 0.x/1.0）----
     動畫：Mixamo clip → normalized humanoid bones（官方 loadMixamoAnimation 作法：來源 rest 世界旋轉補償；normalized rig 本身是 T-pose、identity）。
     靜態姿勢（sit/read/wave/talk）直接寫 normalized bone rotation；表情用 expressionManager；注視用 vrm.lookAt.target。 */
  const VRM_BONE={Hips:'hips',Spine:'spine',Spine1:'chest',Spine2:'upperChest',Neck:'neck',Head:'head',LeftShoulder:'leftShoulder',LeftArm:'leftUpperArm',LeftForeArm:'leftLowerArm',LeftHand:'leftHand',LeftHandThumb1:'leftThumbMetacarpal',LeftHandThumb2:'leftThumbProximal',LeftHandThumb3:'leftThumbDistal',LeftHandIndex1:'leftIndexProximal',LeftHandIndex2:'leftIndexIntermediate',LeftHandIndex3:'leftIndexDistal',LeftHandMiddle1:'leftMiddleProximal',LeftHandMiddle2:'leftMiddleIntermediate',LeftHandMiddle3:'leftMiddleDistal',LeftHandRing1:'leftRingProximal',LeftHandRing2:'leftRingIntermediate',LeftHandRing3:'leftRingDistal',LeftHandPinky1:'leftLittleProximal',LeftHandPinky2:'leftLittleIntermediate',LeftHandPinky3:'leftLittleDistal',RightShoulder:'rightShoulder',RightArm:'rightUpperArm',RightForeArm:'rightLowerArm',RightHand:'rightHand',RightHandThumb1:'rightThumbMetacarpal',RightHandThumb2:'rightThumbProximal',RightHandThumb3:'rightThumbDistal',RightHandIndex1:'rightIndexProximal',RightHandIndex2:'rightIndexIntermediate',RightHandIndex3:'rightIndexDistal',RightHandMiddle1:'rightMiddleProximal',RightHandMiddle2:'rightMiddleIntermediate',RightHandMiddle3:'rightMiddleDistal',RightHandRing1:'rightRingProximal',RightHandRing2:'rightRingIntermediate',RightHandRing3:'rightRingDistal',RightHandPinky1:'rightLittleProximal',RightHandPinky2:'rightLittleIntermediate',RightHandPinky3:'rightLittleDistal',LeftUpLeg:'leftUpperLeg',LeftLeg:'leftLowerLeg',LeftFoot:'leftFoot',LeftToeBase:'leftToes',RightUpLeg:'rightUpperLeg',RightLeg:'rightLowerLeg',RightFoot:'rightFoot',RightToeBase:'rightToes'};
  function mixamoToVRM(clip,srcScene,vrm){ const tracks=[]; const restInv=new THREE.Quaternion(), parentRest=new THREE.Quaternion(), q=new THREE.Quaternion(); srcScene.updateMatrixWorld(true); const srcHips=srcScene.getObjectByName('mixamorigHips')||srcScene.getObjectByName('mixamorig:Hips'); const hipsScale=srcHips?(vrm.humanoid.normalizedRestPose.hips.position[1]/(srcHips.position.y||1)):1; const v0=vrm.meta&&vrm.meta.metaVersion==='0';
    for(const t of clip.tracks){ const [name,prop]=t.name.split('.'); const bone=VRM_BONE[name.replace(/^mixamorig:?/,'')]; const node=bone&&vrm.humanoid.getNormalizedBoneNode(bone); const src=srcScene.getObjectByName(name); if(!node||!src) continue; src.getWorldQuaternion(restInv).invert(); src.parent.getWorldQuaternion(parentRest);
      if(t instanceof THREE.QuaternionKeyframeTrack){ const vals=new Float32Array(t.values.length); for(let i=0;i<t.values.length;i+=4){ q.fromArray(t.values,i); q.premultiply(parentRest).multiply(restInv); vals[i]=q.x; vals[i+1]=q.y; vals[i+2]=q.z; vals[i+3]=q.w; } if(v0){ for(let i=0;i<vals.length;i+=4){ vals[i]=-vals[i]; vals[i+2]=-vals[i+2]; } } tracks.push(new THREE.QuaternionKeyframeTrack(node.name+'.'+prop,Array.from(t.times),Array.from(vals))); }
      else if(t instanceof THREE.VectorKeyframeTrack&&bone==='hips'){ const vals=[]; for(let i=0;i<t.values.length;i+=3){ vals.push(node.position.x, t.values[i+1]*hipsScale, node.position.z); } tracks.push(new THREE.VectorKeyframeTrack(node.name+'.'+prop,Array.from(t.times),vals)); } }
    return new THREE.AnimationClip(clip.name,clip.duration,tracks); }
  const SIT_VRM={LeftUpLeg:[-1.45,0,0],RightUpLeg:[-1.45,0,0],LeftLeg:[1.5,0,0],RightLeg:[1.5,0,0],LeftFoot:[0,0,0],RightFoot:[0,0,0],LeftArm:[0,0,-1.25],RightArm:[0,0,1.25],LeftForeArm:[0,0,0],RightForeArm:[0,0,0]};
  const READ_VRM={LeftArm:[0,0,-1.1],RightArm:[0,0,1.1],LeftForeArm:[0,-1.3,0],RightForeArm:[0,1.3,0]};
  const EXPR_VRM={smile:['happy',0.7],laugh:['happy',1.0],shy:['relaxed',0.8],surprise:['surprised',1.0],worried:['sad',0.7],angry:['angry',0.8],normal:null};
  function buildVRM(spec){ const key=spec.model; const m=ASSETS.manifest[key]; const e=ASSETS.acquireVRM(key); if(!e) throw new Error('no free VRM instance'); const vrm=e.vrm; const model=vrm.scene; const hide=m.hide||[]; model.traverse(o=>{ if(o.isMesh||o.isSkinnedMesh){ o.castShadow=true; o.receiveShadow=false; o.frustumCulled=false; if(hide.some(h=>o.name===h||o.name.startsWith(h))) o.visible=false; } });
    const root=new THREE.Group(); root.name='human'; const H=spec.height||m.height||1.6; vrm.humanoid.resetNormalizedPose(); model.position.set(0,0,0); model.rotation.set(0,0,0); model.scale.setScalar(1); model.updateMatrixWorld(true); const box=new THREE.Box3().setFromObject(model); const mh=box.max.y-box.min.y; const s=H/Math.max(0.1,mh); model.scale.setScalar(s); model.position.y=-box.min.y*s; model.userData.baseY=model.position.y; root.add(model);
    const B={}; for(const n in VRM_BONE){ const node=vrm.humanoid.getNormalizedBoneNode(VRM_BONE[n]); if(node) B[n]=node; }
    const ck=key+':vrm'; if(!ASSETS.clips[ck]){ const src=ASSETS.getRaw(m.anims); const out={}; for(const a of src.animations) out[a.name]=mixamoToVRM(a,src.scene,vrm); ASSETS.clips[ck]=out; }
    // clip 的 track 名稱是 normalized node 名稱；同一模型的每個實例名稱相同，可共用
    const clips=ASSETS.clips[ck]; const mixer=new THREE.AnimationMixer(model); const actions={}; for(const n in clips){ actions[n]=mixer.clipAction(clips[n]); actions[n].enabled=true; }
    const look=new THREE.Object3D(); look.position.set(0,H*0.9,2); root.add(look); if(vrm.lookAt) vrm.lookAt.target=look;
    const headNode=B.Head; let headY=H*0.9; if(headNode){ headNode.updateWorldMatrix(true,false); const wp=new THREE.Vector3(); headNode.getWorldPosition(wp); root.updateMatrixWorld(true); headY=root.worldToLocal(wp).y; }
    root.userData={driver:'vrm',spec,k:H/1.75,parts:{},model,vrm,key,bones:B,look,headY,anim:{t:Math.random()*10,expr:'normal',pose:'idle',mixer,actions,cur:null,static:false,mouth:0,blink:2+Math.random()*3,blinkT:0}}; if(actions.idle){ actions.idle.play(); root.userData.anim.cur='idle'; }
    return root; }
  C.release=function(h){ const u=h&&h.userData; if(!u||u.driver!=='vrm') return; try{ for(const n in u.anim.actions) u.anim.actions[n].stop(); u.anim.mixer.stopAllAction(); u.vrm.humanoid.resetNormalizedPose(); if(u.vrm.expressionManager) u.vrm.expressionManager.expressions.forEach(ex=>u.vrm.expressionManager.setValue(ex.expressionName,0)); }catch(e){} ASSETS.releaseVRM(u.key,u.vrm); };
  function animateVRM(h,dt,st){ const u=h.userData; const a=u.anim; a.t+=dt; const pose=st.pose||'idle'; const B=u.bones; const spd=st.speed||0; const vrm=u.vrm;
    if(pose==='sit'||pose==='read'){ if(!a.static){ for(const n in a.actions) a.actions[n].stop(); a.static=true; a.cur=null; vrm.humanoid.resetNormalizedPose(); } u.model.position.y=(u.model.userData.baseY||0)-0.47*u.k; setBones(B,SIT_VRM,1); if(pose==='read'){ setBones(B,READ_VRM,1); if(B.Head) B.Head.rotation.set(0.35+Math.sin(a.t*0.6)*0.02,0,0); } else { if(B.Head) B.Head.rotation.set(Math.sin(a.t*0.7)*0.03,Math.sin(a.t*0.4)*0.15,0); } if(B.Spine) B.Spine.rotation.set(0.06,0,0); }
    else { if(a.static){ a.static=false; u.model.position.y=u.model.userData.baseY||0; vrm.humanoid.resetNormalizedPose(); } const clipName=POSE_CLIP[pose]||'idle'; if(a.cur!==clipName&&a.actions[clipName]){ const prev=a.cur&&a.actions[a.cur]; const next=a.actions[clipName]; next.reset().setEffectiveWeight(1).fadeIn(0.22).play(); if(prev) prev.fadeOut(0.22); a.cur=clipName; } const act=a.actions[a.cur]; if(act){ act.timeScale= a.cur==='walk'?Math.max(0.6,spd/1.45): (a.cur==='run'?Math.max(0.7,spd/4.1):1); } a.mixer.update(dt);
      if(pose==='wave'&&B.RightArm){ const g=Math.sin(a.t*7); B.RightArm.rotation.set(0,0,-0.9); if(B.RightForeArm) B.RightForeArm.rotation.set(0,0,-1.6+g*0.25); if(B.Head) B.Head.rotation.z+=0.08; }
      if(pose==='talk'&&B.Head){ B.Head.rotation.x+=Math.sin(a.t*1.4)*0.05; B.Head.rotation.y+=Math.sin(a.t*0.8)*0.08; if(B.RightForeArm){ const g=Math.sin(a.t*2.2); B.RightForeArm.rotation.y+=0.6+g*0.15; } } }
    // 注視（眼睛＋頭）
    if(st.lookAt){ const local=h.worldToLocal(new THREE.Vector3(st.lookAt.x,u.headY,st.lookAt.z)); u.look.position.copy(local); if(B.Head){ const dx=st.lookAt.x-h.position.x, dz=st.lookAt.z-h.position.z; let ang=Math.atan2(dx,dz)-h.rotation.y; ang=Math.atan2(Math.sin(ang),Math.cos(ang)); ang=Math.max(-0.7,Math.min(0.7,ang)); B.Head.rotation.y+=ang*0.6; if(B.Spine1) B.Spine1.rotation.y+=ang*0.15; } } else { u.look.position.set(0,u.headY,3); }
    // 表情：眨眼、嘴型
    const em=vrm.expressionManager; if(em){ a.blink-=dt; if(a.blink<=0){ a.blinkT=0.14; a.blink=2.5+Math.random()*3.5; } if(a.blinkT>0){ a.blinkT-=dt; em.setValue('blink',a.blinkT>0.07?1:(a.blinkT/0.07)); } else em.setValue('blink',0); const target=pose==='talk'?(0.15+Math.abs(Math.sin(a.t*9))*0.5):0; a.mouth+=(target-a.mouth)*Math.min(1,dt*14); em.setValue('aa',a.mouth); }
    vrm.update(dt); }
  C.setExprVRM=function(h,expr){ const u=h.userData; u.anim.expr=expr; const em=u.vrm.expressionManager; if(!em) return; for(const k in EXPR_VRM){ const e=EXPR_VRM[k]; if(e) em.setValue(e[0],0); } const e=EXPR_VRM[expr]; if(e) em.setValue(e[0],e[1]); };
  // ---- 建立 ----
  // 建立順序：VRM（spec.model）→ GLB（spec.model 或 spec.fallbackModel，例如主角的 TEMP_PLAYER_DEV_MODEL）→ 程序化 placeholder
  C.build=function(spec){ if(C.canVRM(spec)){ try{ return buildVRM(spec); }catch(e){ console.warn('VRM character failed, fallback',e); } } if(C.canGLB(spec)){ try{ return buildGLB(spec); }catch(e){ console.warn('GLB character failed, fallback to procedural',e); } } if(spec.fallbackModel){ const s2=Object.assign({},spec,{model:spec.fallbackModel,fallbackModel:null}); if(C.canGLB(s2)){ try{ return buildGLB(s2); }catch(e){ console.warn('fallback GLB failed',e); } } } const o=P3.build(spec); o.userData.driver='proc'; return o; };
  function buildGLB(spec){ const key=spec.model; const m=ASSETS.manifest[key]; const tpl=ASSETS.getRaw(key); const model=THREE_JSM.SkeletonUtils.clone(tpl.scene); const hide=m.hide||[]; let headMesh=null; model.traverse(o=>{ if(o.isMesh||o.isSkinnedMesh){ o.castShadow=true; o.receiveShadow=false; o.frustumCulled=false; if(hide.some(h=>o.name.includes(h))) o.visible=false; if(o.morphTargetDictionary&&o.morphTargetDictionary.mouthSmile!==undefined) headMesh=o; } });
    const root=new THREE.Group(); root.name='human'; const H=spec.height||m.height||1.75; const box=new THREE.Box3().setFromObject(model); const mh=box.max.y-box.min.y; const s=H/Math.max(0.1,mh); model.scale.setScalar(s); model.position.y=-box.min.y*s; model.userData.baseY=model.position.y; root.add(model);
    const bones={}; model.traverse(o=>{ if(o.isBone) bones[o.name]=o; }); const clips=clipsFor(key); const mixer=new THREE.AnimationMixer(model); const actions={}; for(const n in clips){ actions[n]=mixer.clipAction(clips[n]); actions[n].enabled=true; }
    root.userData={driver:'glb',spec,k:H/1.75,parts:{},model,bones,headMesh,anim:{t:Math.random()*10,expr:'normal',pose:'idle',mixer,actions,cur:null,static:false,mouth:0}}; if(actions.idle){ actions.idle.play(); root.userData.anim.cur='idle'; }
    return root; }
  // ---- 動畫 ----
  const SIT={LeftUpLeg:[1.45,0,0.08],RightUpLeg:[1.45,0,-0.08],LeftLeg:[1.5,0,0],RightLeg:[1.5,0,0],LeftFoot:[0,0,0],RightFoot:[0,0,0],LeftArm:[0.9,0,0.35],RightArm:[0.9,0,-0.35],LeftForeArm:[0,0,0],RightForeArm:[0,0,0]};
  const READ={LeftArm:[1.2,0,0.9],RightArm:[1.2,0,-0.9],LeftForeArm:[0,0,1.2],RightForeArm:[0,0,-1.2]};
  function setBones(bones,tab,blend){ for(const n in tab){ const b=bones[n]; if(!b) continue; const r=tab[n]; if(blend>=1){ b.rotation.set(r[0],r[1],r[2]); } else { b.rotation.x+=(r[0]-b.rotation.x)*blend; b.rotation.y+=(r[1]-b.rotation.y)*blend; b.rotation.z+=(r[2]-b.rotation.z)*blend; } } }
  C.animate=function(h,dt,st){ const u=h.userData; if(u.driver==='vrm'){ animateVRM(h,dt,st); return; } if(u.driver!=='glb'){ P3.animate(h,dt,st); return; } const a=u.anim; a.t+=dt; const pose=st.pose||'idle'; const B=u.bones; const spd=st.speed||0;
    if(pose==='sit'||pose==='read'){ if(!a.static){ for(const n in a.actions) a.actions[n].stop(); a.static=true; a.cur=null; } u.model.position.y=(u.model.userData.baseY||0)-0.47*u.k; setBones(B,SIT,1); if(pose==='read'){ setBones(B,READ,1); if(B.Head) B.Head.rotation.set(0.35+Math.sin(a.t*0.6)*0.02,0,0); } else { if(B.Head) B.Head.rotation.set(Math.sin(a.t*0.7)*0.03,Math.sin(a.t*0.4)*0.15,0); } if(B.Spine) B.Spine.rotation.set(0.06,0,0); }
    else { if(a.static){ a.static=false; u.model.position.y=u.model.userData.baseY||0; for(const n in B){ B[n].rotation.set(0,0,0); } } const clipName=POSE_CLIP[pose]||'idle'; if(a.cur!==clipName&&a.actions[clipName]){ const prev=a.cur&&a.actions[a.cur]; const next=a.actions[clipName]; next.reset().setEffectiveWeight(1).fadeIn(0.22).play(); if(prev) prev.fadeOut(0.22); a.cur=clipName; } const act=a.actions[a.cur]; if(act){ act.timeScale= a.cur==='walk'?Math.max(0.6,spd/1.45): (a.cur==='run'?Math.max(0.7,spd/4.1):1); } a.mixer.update(dt);
      if(pose==='wave'&&B.RightArm){ const g=Math.sin(a.t*7); B.RightArm.rotation.set(-0.2,0,-2.4+g*0.15); if(B.RightForeArm) B.RightForeArm.rotation.set(0.1,0,-0.5-Math.abs(g)*0.3); if(B.Head) B.Head.rotation.z+=0.08; }
      if(pose==='talk'&&B.Head){ B.Head.rotation.x+=Math.sin(a.t*1.4)*0.05; B.Head.rotation.y+=Math.sin(a.t*0.8)*0.08; if(B.RightArm){ const g=Math.sin(a.t*2.2); B.RightArm.rotation.z-=0.35+g*0.1; if(B.RightForeArm) B.RightForeArm.rotation.z-=0.9+g*0.15; } } }
    // 注視
    if(st.lookAt&&B.Head){ const dx=st.lookAt.x-h.position.x, dz=st.lookAt.z-h.position.z; let ang=Math.atan2(dx,dz)-h.rotation.y; ang=Math.atan2(Math.sin(ang),Math.cos(ang)); ang=Math.max(-0.7,Math.min(0.7,ang)); B.Head.rotation.y+=ang*0.8; if(B.Spine1) B.Spine1.rotation.y+=ang*0.15; }
    // 嘴型（說話時）與表情
    if(u.headMesh){ const d=u.headMesh.morphTargetDictionary, inf=u.headMesh.morphTargetInfluences; if(d.mouthOpen!==undefined){ const target=pose==='talk'?(0.15+Math.abs(Math.sin(a.t*9))*0.35):0; a.mouth+=(target-a.mouth)*Math.min(1,dt*14); inf[d.mouthOpen]=a.mouth; } } };
  C.setExpr=function(h,expr){ const u=h.userData; if(u.driver==='vrm'){ C.setExprVRM(h,expr); return; } if(u.driver!=='glb'){ P3.setExpr(h,expr); return; } u.anim.expr=expr; const hm=u.headMesh; if(!hm) return; const d=hm.morphTargetDictionary, inf=hm.morphTargetInfluences; if(d.mouthSmile!==undefined) inf[d.mouthSmile]=(expr==='smile'?0.55:(expr==='laugh'?0.9:(expr==='shy'?0.3:0))); };
  // 頭部高度（運鏡用）
  C.headY=function(h){ const u=h.userData; const k=u.k||1; const a=u.anim; const sit=a&&(a.pose==='sit'||a.pose==='read'); if(u.driver==='vrm'){ return (u.anim.static?u.headY-0.47*k:u.headY); } if(u.driver==='glb'){ const st=(u.anim.static); return (st?1.16:1.62)*k; } return (sit?1.19:1.62)*k; };
  C.isGLB=function(h){ return h&&h.userData&&(h.userData.driver==='glb'||h.userData.driver==='vrm'); };
  return C;
})();
