/* ===== CONDITIONAL STORY EVENT SYSTEM（data-driven；schema 見 STORY_EVENT_SCHEMA.md）
   事件資料在 src/data/events.js（STORY_EVENTS）。引擎負責：條件評估、觸發（auto / interact / enter）、對話執行（ADV 演出）、選項、後果（flags / memory / relationship / knowledge / professor / grad）、冷卻與一次性、存檔。 ===== */
'use strict';
const EVENTS = (function(){
  const X={}; let GM=null, G=null;
  const ALIAS={heroine_01:'an',heroine_05:'sis',prof_zhou:'prof'};
  X.bind=function(gm){ GM=gm; G=gm.G; if(!G.events) G.events={done:{},last:{},count:0}; };
  X.npcOf=function(charId){ if(!GM||!GM.npc) return null; return GM.npc[charId]||GM.npc[ALIAS[charId]]||null; };
  X.charOf=function(npc){ if(!npc) return null; if(npc.charId) return npc.charId; for(const k in ALIAS) if(ALIAS[k]===npc.id) return k; return npc.id; };
  const h=()=>G.hour%24;
  // ---- 條件評估 ----
  X.check=function(ev,ctx){ ctx=ctx||{}; const F=G.flags||{}; if(ev.once&&G.events.done[ev.id]) return false; if(ev.cooldown_days&&G.events.last[ev.id]!==undefined&&G.day-G.events.last[ev.id]<ev.cooldown_days) return false; if(ev.max_times&&(G.events.done[ev.id]||0)>=ev.max_times) return false;
    if(ev.location&&ev.location!=='any'){ const locs=Array.isArray(ev.location)?ev.location:[ev.location]; if(!locs.includes(G.zone)) return false; }
    if(ev.time){ const hh=h(); const [a,b]=ev.time; if(b<=24){ if(hh<a||hh>=b) return false; } else { if(!(hh>=a||hh<b-24)) return false; } }
    if(ev.weekday&&!ev.weekday.includes(G.weekday)) return false; if(ev.day_min&&G.day<ev.day_min) return false; if(ev.day_max&&G.day>ev.day_max) return false; if(ev.weather&&G.weather!==ev.weather) return false; if(ev.not_weather&&G.weather===ev.not_weather) return false;
    return X.cond(ev.prereq,ctx); };
  X.cond=function(c,ctx){ if(!c) return true; const F=G.flags||{}; if(c.flags&&!c.flags.every(f=>F[f])) return false; if(c.notFlags&&c.notFlags.some(f=>F[f])) return false; if(c.memory&&!c.memory.every(m=>SOCIAL.has(m.npc,m.tag))) return false; if(c.notMemory&&c.notMemory.some(m=>SOCIAL.has(m.npc,m.tag))) return false;
    if(c.stage){ const st=SOCIAL.STAGES.indexOf(SOCIAL.stage(c.stage.npc)); if(c.stage.min&&st<SOCIAL.STAGES.indexOf(c.stage.min)) return false; if(c.stage.max&&st>SOCIAL.STAGES.indexOf(c.stage.max)) return false; }
    if(c.rel){ for(const id in c.rel){ const r=SOCIAL.rel(id); for(const dim in c.rel[id]){ const rng=c.rel[id][dim]; if(rng.min!==undefined&&r[dim]<rng.min) return false; if(rng.max!==undefined&&r[dim]>rng.max) return false; } } }
    if(c.events&&!c.events.every(e=>G.events.done[e])) return false; if(c.notEvents&&c.notEvents.some(e=>G.events.done[e])) return false;
    if(c.knowledge&&typeof LEGAL!=='undefined'){ for(const k of c.knowledge){ const st=LEGAL.stateOf(k.qid); const order=LEGAL.STATES; if(k.min&&order.indexOf(st)<order.indexOf(k.min)) return false; if(k.max&&order.indexOf(st)>order.indexOf(k.max)) return false; } }
    if(c.grad){ const gi=SOCIAL.GRAD.indexOf(G.social.grad.interest); if(c.grad.min&&gi<SOCIAL.GRAD.indexOf(c.grad.min)) return false; if(c.grad.max&&gi>SOCIAL.GRAD.indexOf(c.grad.max)) return false; }
    if(c.energy&&(G.energy<(c.energy.min||0)||G.energy>(c.energy.max||100))) return false; if(c.money&&(G.money<(c.money.min||-1e9))) return false; if(c.choice){ for(const k in c.choice){ if((G.choices||{})[k]!==c.choice[k]) return false; } }
    if(c.custom&&typeof c.custom==='function'&&!c.custom(G,GM)) return false; return true; };
  // ---- 觸發：tick（auto）----
  X.tick=function(dt){ if(!GM||!G||GM.E.player.busy||GM.D.active||ADV.active) return; const P=GM.E.player.obj.position; for(const ev of STORY_EVENTS){ if(ev.trigger!=='auto') continue; if(!X.check(ev)) continue; if(ev.near){ if(ev.near.npc){ const n=X.npcOf(ev.near.npc); if(!n) continue; if(Math.hypot(n.obj.position.x-P.x,n.obj.position.z-P.z)>(ev.near.r||4)) continue; } else if(Math.hypot(ev.near.x-P.x,ev.near.z-P.z)>(ev.near.r||5)) continue; } if(ev.random_weight!==undefined&&Math.random()>ev.random_weight/60) continue; X.run(ev); return true; } return false; };
  // 觸發：進入區域
  X.onEnter=function(zoneId){ if(!GM||!G) return false; for(const ev of STORY_EVENTS){ if(ev.trigger!=='enter') continue; if(!X.check(ev)) continue; if(ev.random_weight!==undefined&&Math.random()>ev.random_weight) continue; X.run(ev); return true; } return false; };
  // 觸發：與 NPC 互動（回傳 true 表示已處理）
  X.onInteract=function(charId){ if(!GM||!G) return false; const list=STORY_EVENTS.filter(ev=>ev.trigger==='interact'&&ev.participants&&ev.participants[0]===charId); list.sort((a,b)=>(b.priority||0)-(a.priority||0)); for(const ev of list){ if(!X.check(ev)) continue; if(ev.random_weight!==undefined&&Math.random()>ev.random_weight) continue; X.run(ev); return true; } return false; };
  // ---- 執行 ----
  function subst(t){ return String(t).replace(/\{name\}/g,G.name).replace(/\{npc:([a-z0-9_]+)\}/g,(m,id)=>SOCIAL.displayName(id)); }
  function ensureNPC(ev){ if(!ev.spawn) return null; const id=ev.spawn.npc; let n=X.npcOf(id); if(n) return n; const c=CHARACTERS[id]; if(!c||!GM.spawnCharacter) return null; const P=GM.E.player.obj; let x,z; if(ev.spawn.at&&ev.spawn.at.x!==undefined){ x=ev.spawn.at.x; z=ev.spawn.at.z; } else { const d=ev.spawn.dist||2.2; const yaw=P.rotation.y; x=P.position.x+Math.sin(yaw)*d; z=P.position.z+Math.cos(yaw)*d; } n=GM.spawnCharacter(id,x,z,{yaw:Math.atan2(P.position.x-x,P.position.z-z),pose:ev.spawn.pose||'idle'}); return n; }
  X.run=async function(ev,opts){ opts=opts||{}; if(X.running) return; X.running=ev.id; try{ GM.sceneBegin(); const npcs=[]; if(ev.spawn){ const n=ensureNPC(ev); if(n) npcs.push(n); } for(const pid of ev.participants||[]){ const n=X.npcOf(pid); if(n&&!npcs.includes(n)) npcs.push(n); }
      // 3D：面對玩家、短暫運鏡
      const P=GM.E.player; for(const n of npcs){ if(!n.seat){ GM.face(n,P.obj.position.x,P.obj.position.z); } n.lookAt=P.obj.position; if(n.beh==='follow') n._wasFollow=true; } if(npcs[0]&&!npcs[0].seat) GM.face(P,npcs[0].obj.position.x,npcs[0].obj.position.z); if(npcs[0]) GM.cine('two',P.obj,npcs[0].obj);
      if(ev.player_seat&&GM.E.zone.seats){ const st=GM.E.zone.seats.find(x=>x.row===ev.player_seat[0]&&x.col===ev.player_seat[1])||GM.E.zone.seats[0]; if(st){ await GM.walkTo(P,st.x,st.z+0.6); GM.sitAt(P,st); X._playerSeated=true; } }
      const parts=(ev.participants||[]).filter(id=>CHARACTERS[id]); const advOpts={background:ev.background||'blur',mainSide:ev.mainSide||'right'}; if(parts[0]) advOpts.right={charId:parts[0],expression:'neutral'}; if(parts[1]) advOpts.left={charId:parts[1],expression:'neutral'}; if(ev.cg_id) advOpts.cg=ev.cg_id; ADV.preload(parts); ADV.begin(advOpts); if(ev.title&&!opts.noTitle) GM.caption('',ev.title,1500); await GM.sleep(350);
      for(const pid of parts){ SOCIAL.meet(pid,ev.location&&ev.location!=='any'?(Array.isArray(ev.location)?ev.location[0]:ev.location):G.zone); }
      await X.runLines(ev.dialogue||[],ev); X.applyConsequences(ev.consequences); G.events.done[ev.id]=(G.events.done[ev.id]||0)+1; G.events.last[ev.id]=G.day; G.events.count++; GM.memo(ev.title||ev.id);
      ADV.end(); if(X._playerSeated){ GM.standUp(P); X._playerSeated=false; } GM.sceneEnd(); for(const n of npcs){ n.lookAt=null; } if(ev.after&&typeof ev.after==='function') ev.after(G,GM,npcs); if(ev.despawn&&npcs[0]&&GM.despawnLater) GM.despawnLater(npcs[0],ev.despawn); GM.autosave(); if(ev.next_event){ const nx=STORY_EVENTS.find(e=>e.id===ev.next_event); if(nx&&X.check(nx)){ X.running=null; return X.run(nx,{noTitle:true}); } } }catch(e){ console.error('event error',ev.id,e); ADV.end(); GM.sceneEnd(); } finally{ X.running=null; } };
  X.runLines=async function(lines,ev){ const labels={}; lines.forEach((l,i)=>{ if(l.label) labels[l.label]=i; }); let i=0; let guard=0; while(i<lines.length&&guard++<500){ const l=lines[i]; i++; if(l.if&&!X.cond(l.if)) continue; if(l.unless&&X.cond(l.unless)) continue; if(l.goto!==undefined&&l.text===undefined&&!l.choice){ i=labels[l.goto]!==undefined?labels[l.goto]:i; continue; } if(l.end) break;
      if(l.consequences) X.applyConsequences(l.consequences); if(l.set) for(const k in l.set) G.flags[k]=l.set[k]; if(l.mem) for(const m of l.mem) SOCIAL.remember(m.npc,m.tag,m.note); if(l.rel) for(const id in l.rel) SOCIAL.adjust(id,l.rel[id]); if(l.note) GM.addNote(l.note.id,l.note.title,l.note.body); if(l.knowledge&&typeof LEGAL!=='undefined') LEGAL.apply(l.knowledge); if(l.advance) GM.advance(l.advance); if(l.cine&&!ADV.active){ const n=X.npcOf(l.cine.npc||(ev.participants||[])[0]); GM.cine(l.cine.shot||l.cine,GM.E.player.obj,n&&n.obj); }
      if(l.expression&&l.speaker&&l.text===undefined){ ADV.speaker(l.speaker,l.expression,l.outfit); continue; }
      if(l.legal&&typeof LEGAL!=='undefined'){ await LEGAL.ask(l.legal,ev); continue; }
      if(l.text!==undefined){ const sp=l.speaker; let who=null; if(sp&&sp!=='player'&&sp!=='narrator'){ ADV.speaker(sp,l.expression,l.outfit); const n=X.npcOf(sp); who={name:SOCIAL.displayName(sp),obj:n&&n.obj,charId:sp,pose:n&&n.pose,idlePose:n&&n.idlePose}; if(n&&l.expression) CHAR.setExpr(n.obj,{neutral:'normal',smile:'smile',laugh:'laugh',surprised:'surprise',embarrassed:'shy',annoyed:'worried',sad:'worried',serious:'normal',tired:'normal',thinking:'normal'}[l.expression]||'normal'); } else if(sp==='player'){ who={name:G.name}; ADV.speaker(null); } const text=subst(l.text); ADV.log(who?who.name:'',text); await GM.say(who,text,{keepPose:!!(who&&who.pose==='sit')}); }
      if(l.choice){ const opts=l.choice.filter(c=>!c.if||X.cond(c.if)).map(c=>({t:subst(c.text),hint:c.hint,dim:c.dim,_c:c})); const k=await GM.choose(opts); const c=opts[k]._c; ADV.log(G.name,'▶ '+subst(c.text)); if(c.consequences) X.applyConsequences(c.consequences); if(c.set) for(const kk in c.set) G.flags[kk]=c.set[kk]; if(c.mem) for(const m of c.mem) SOCIAL.remember(m.npc,m.tag,m.note); if(c.rel) for(const id in c.rel) SOCIAL.adjust(id,c.rel[id]); if(c.choiceKey) { G.choices=G.choices||{}; G.choices[c.choiceKey]=c.value!==undefined?c.value:k; } if(c.next){ const nx=STORY_EVENTS.find(e=>e.id===c.next); if(nx){ X.running=null; await X.run(nx,{noTitle:true}); return; } } if(c.goto!==undefined){ i=labels[c.goto]!==undefined?labels[c.goto]:i; } if(c.end) break; } } };
  X.applyConsequences=function(c){ if(!c) return; if(c.flags) for(const k in c.flags) G.flags[k]=c.flags[k]; if(c.mem) for(const m of c.mem) SOCIAL.remember(m.npc,m.tag,m.note); if(c.rel) for(const id in c.rel) SOCIAL.adjust(id,c.rel[id]); if(c.prof) for(const id in c.prof){ const p=c.prof[id]; SOCIAL.profEvent(id,p.kind||'part',p.delta||1,p.note); } if(c.grad){ if(c.grad.set) SOCIAL.gradSet(c.grad.set,c.grad.field); else SOCIAL.gradBump(c.grad.bump||'event',c.grad.field); } if(c.energy) GM.energy(c.energy); if(c.money) GM.money(c.money); if(c.advance) GM.advance(c.advance); if(c.memo) GM.memo(c.memo); if(c.note) GM.addNote(c.note.id,c.note.title,c.note.body); if(c.knowledge&&typeof LEGAL!=='undefined') LEGAL.apply(c.knowledge); if(c.goal) GM.setGoal(c.goal); if(c.cg&&ADV.cg) ADV.cg(c.cg); };
  // 事件列表（供筆記本／review）
  X.list=function(){ return STORY_EVENTS.map(e=>({id:e.id,title:e.title,done:G.events.done[e.id]||0,eligible:X.check(e)})); };
  return X;
})();
