/* ===== 3D 世界素材：材質貼圖（畫布）、建築生成、樹木、道具 ===== */
'use strict';
const W3 = (function(){
  const mat=(c,o)=>P3.M(c,Object.assign({rough:0.92},o||{})), G=P3.G, outline=()=>null, shade=P3.shade; const toonMap=(map)=>new THREE.MeshStandardMaterial({map,roughness:0.95,metalness:0});
  const texCache={};
  function canvasTex(key,w,h,fn,opts){ if(texCache[key]) return texCache[key]; const c=document.createElement('canvas'); c.width=w; c.height=h; const x=c.getContext('2d'); fn(x,w,h); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; t.wrapS=t.wrapT=THREE.RepeatWrapping; t.anisotropy=4; if(opts&&opts.nearest){ t.magFilter=THREE.NearestFilter; } texCache[key]=t; return t; }
  // ---- 地面貼圖 ----
  function grassTex(){ return canvasTex('grass',256,256,(x,w,h)=>{ x.fillStyle='#93bd75'; x.fillRect(0,0,w,h); for(let i=0;i<900;i++){ const px=Math.random()*w, py=Math.random()*h; x.fillStyle=Math.random()<0.5?'#86b26a':'#a2c985'; x.fillRect(px,py,2+Math.random()*3,1+Math.random()*2); } for(let i=0;i<60;i++){ x.fillStyle='rgba(120,160,95,0.35)'; x.beginPath(); x.ellipse(Math.random()*w,Math.random()*h,8+Math.random()*14,4+Math.random()*6,0,0,Math.PI*2); x.fill(); } }); }
  function pathTex(){ return canvasTex('path',256,256,(x,w,h)=>{ x.fillStyle='#ded2b8'; x.fillRect(0,0,w,h); const tw=64,th=64; for(let j=0;j<h/th;j++) for(let i=0;i<w/tw;i++){ const v=(Math.random()*12)|0; x.fillStyle='rgb('+(216+v)+','+(203+v)+','+(178+v)+')'; x.fillRect(i*tw+1,j*th+1,tw-2,th-2); } x.strokeStyle='rgba(120,100,80,0.28)'; x.lineWidth=2; for(let i=0;i<=w;i+=tw){ x.beginPath(); x.moveTo(i,0); x.lineTo(i,h); x.stroke(); } for(let j=0;j<=h;j+=th){ x.beginPath(); x.moveTo(0,j); x.lineTo(w,j); x.stroke(); } for(let i=0;i<40;i++){ x.fillStyle='rgba(90,80,70,0.08)'; x.beginPath(); x.ellipse(Math.random()*w,Math.random()*h,6,3,0,0,Math.PI*2); x.fill(); } }); }
  function asphaltTex(){ return canvasTex('asphalt',256,256,(x,w,h)=>{ x.fillStyle='#7d7a76'; x.fillRect(0,0,w,h); for(let i=0;i<1400;i++){ x.fillStyle=Math.random()<0.5?'#726f6b':'#8a8783'; x.fillRect(Math.random()*w,Math.random()*h,2,2); } }); }
  function brickTex(base){ return canvasTex('brick'+base,256,256,(x,w,h)=>{ x.fillStyle=base||'#c58b74'; x.fillRect(0,0,w,h); const bw=32,bh=14; for(let j=0;j<h/bh;j++){ const off=(j%2)*bw/2; for(let i=-1;i<w/bw+1;i++){ const v=(Math.random()*18-9)|0; const c=new THREE.Color(base||'#c58b74'); c.offsetHSL(0,0,v/255); x.fillStyle='#'+c.getHexString(); x.fillRect(i*bw+off+1,j*bh+1,bw-2,bh-2); } } x.fillStyle='rgba(255,240,220,0.35)'; for(let j=0;j<=h;j+=bh){ x.fillRect(0,j,w,1); } }); }
  function stoneTex(base){ return canvasTex('stone'+base,256,256,(x,w,h)=>{ x.fillStyle=base||'#e8dcc4'; x.fillRect(0,0,w,h); for(let i=0;i<500;i++){ x.fillStyle='rgba(0,0,0,'+(Math.random()*0.05)+')'; x.fillRect(Math.random()*w,Math.random()*h,3,3); } x.strokeStyle='rgba(90,70,50,0.18)'; x.lineWidth=2; for(let j=0;j<=h;j+=42){ x.beginPath(); x.moveTo(0,j); x.lineTo(w,j); x.stroke(); } for(let j=0;j<h/42;j++){ const off=(j%2)*60; for(let i=off;i<=w;i+=120){ x.beginPath(); x.moveTo(i,j*42); x.lineTo(i,j*42+42); x.stroke(); } } }); }
  // ---- 立面貼圖：窗戶 ----
  // opts: {floors, cols, wall, frame, glass, ground(bool), night, style:'band'|'grid'|'arch'|'slit', bandColor}
  function facadeTex(key,opts){ const W=opts.w||512, H=opts.h||512; return canvasTex(key+(opts.night?'_n':''),W,H,(x,w,h)=>{ x.fillStyle=opts.wall; x.fillRect(0,0,w,h); for(let i=0;i<600;i++){ x.fillStyle='rgba(0,0,0,'+(Math.random()*0.04)+')'; x.fillRect(Math.random()*w,Math.random()*h,2,2); }
      const floors=opts.floors, cols=opts.cols; const fh=h/floors; const cw=w/cols; const glass= opts.night?'#3b4a66':(opts.glass||'#bcd6df'); const lit=opts.night;
      for(let f=0;f<floors;f++){ const y0=h-(f+1)*fh; // f=0 ground
        if(opts.style==='band'){ const wy=y0+fh*0.22, wh=fh*0.5; x.fillStyle=opts.bandColor||shade(opts.wall,0.12); x.fillRect(0,y0+fh*0.15,w,fh*0.62); for(let c=0;c<cols;c++){ const x0=c*cw+cw*0.08; const ww=cw*0.84; x.fillStyle=lit&&Math.random()<0.55?'#f6dfa8':glass; x.fillRect(x0,wy,ww,wh); const g=x.createLinearGradient(x0,wy,x0+ww,wy+wh); g.addColorStop(0,'rgba(255,255,255,0.35)'); g.addColorStop(0.5,'rgba(255,255,255,0.05)'); g.addColorStop(1,'rgba(255,255,255,0.25)'); x.fillStyle=g; x.fillRect(x0,wy,ww,wh); x.strokeStyle=opts.frame||'#5b5f66'; x.lineWidth=3; x.strokeRect(x0,wy,ww,wh); x.beginPath(); x.moveTo(x0+ww/2,wy); x.lineTo(x0+ww/2,wy+wh); x.stroke(); } }
        else if(opts.style==='slit'){ for(let c=0;c<cols;c++){ const x0=c*cw+cw*0.3; const ww=cw*0.4; const wy=y0+fh*0.12, wh=fh*0.74; x.fillStyle=lit&&Math.random()<0.5?'#f6dfa8':glass; x.fillRect(x0,wy,ww,wh); x.strokeStyle=opts.frame||'#3a3f46'; x.lineWidth=3; x.strokeRect(x0,wy,ww,wh); x.fillStyle='rgba(255,255,255,0.25)'; x.fillRect(x0,wy,ww*0.35,wh); } }
        else if(opts.style==='arch'){ for(let c=0;c<cols;c++){ const x0=c*cw+cw*0.18; const ww=cw*0.64; const wy=y0+fh*0.18, wh=fh*0.7; x.fillStyle=lit&&Math.random()<0.5?'#f6dfa8':glass; x.beginPath(); x.moveTo(x0,wy+wh); x.lineTo(x0,wy+ww/2); x.arc(x0+ww/2,wy+ww/2,ww/2,Math.PI,0); x.lineTo(x0+ww,wy+wh); x.closePath(); x.fill(); x.strokeStyle=opts.frame||'#6b5a4a'; x.lineWidth=4; x.stroke(); x.fillStyle='rgba(255,255,255,0.25)'; x.fillRect(x0+3,wy+ww/2,ww*0.3,wh-ww/2-3); } }
        else { for(let c=0;c<cols;c++){ const x0=c*cw+cw*0.16; const ww=cw*0.68; const wy=y0+fh*0.2, wh=fh*0.55; x.fillStyle=lit&&Math.random()<0.5?'#f6dfa8':glass; x.fillRect(x0,wy,ww,wh); x.fillStyle='rgba(255,255,255,0.25)'; x.fillRect(x0,wy,ww*0.4,wh); x.strokeStyle=opts.frame||'#5b5f66'; x.lineWidth=3; x.strokeRect(x0,wy,ww,wh); x.beginPath(); x.moveTo(x0,wy+wh/2); x.lineTo(x0+ww,wy+wh/2); x.moveTo(x0+ww/2,wy); x.lineTo(x0+ww/2,wy+wh); x.stroke(); } }
        // 樓層分隔線
        x.fillStyle='rgba(0,0,0,0.12)'; x.fillRect(0,y0+fh-3,w,3); }
      if(opts.ground==='glass'){ x.fillStyle=lit?'#f2d98a':'#a9c9d6'; x.fillRect(0,h-fh,w,fh); x.strokeStyle='#3a3f46'; x.lineWidth=4; for(let c=0;c<=cols*2;c++){ x.beginPath(); x.moveTo(c*w/(cols*2),h-fh); x.lineTo(c*w/(cols*2),h); x.stroke(); } x.strokeRect(0,h-fh,w,fh); x.fillStyle='rgba(255,255,255,0.2)'; x.fillRect(0,h-fh,w,fh*0.4); }
    }); }
  function signTex(text,opts){ opts=opts||{}; return canvasTex('sign_'+text+JSON.stringify(opts),512,128,(x,w,h)=>{ x.fillStyle=opts.bg||'rgba(0,0,0,0)'; x.fillRect(0,0,w,h); x.fillStyle=opts.color||'#3b2a1e'; x.font='bold '+(opts.size||64)+'px "Noto Sans TC","PingFang TC","Microsoft JhengHei",sans-serif'; x.textAlign='center'; x.textBaseline='middle'; x.fillText(text,w/2,h/2); }); }
  function signPlane(text,w,h,opts){ const t=signTex(text,opts); const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,transparent:true,depthWrite:false})); m.renderOrder=3; return m; }
  // ---- 建築 ----
  // spec: {w,h,d, floors, style, wall, glass, frame, roof:'flat'|'hip'|'parapet', roofColor, entrance:{w,h,canopy,steps,glass}, sign, brick:true, cols}
  function building(spec){ const g=new THREE.Group(); const w=spec.w,h=spec.h,d=spec.d; const floors=spec.floors||Math.round(h/3.4); const key='fac_'+(spec.key||JSON.stringify(spec).length+spec.style+spec.wall);
    const mk=(kk,width,cols)=>{ const day=facadeTex(kk,{floors,cols,wall:spec.wall,glass:spec.glass,frame:spec.frame,style:spec.style,ground:spec.ground,bandColor:spec.bandColor,w:512,h:512}); const night=facadeTex(kk,{floors,cols,wall:spec.wall,glass:spec.glass,frame:spec.frame,style:spec.style,ground:spec.ground,bandColor:spec.bandColor,night:true,w:512,h:512}); return {day,night}; };
    const colsF=spec.cols||Math.max(3,Math.round(w/3.2)), colsS=Math.max(2,Math.round(d/3.2));
    const F=mk(key+'F',w,colsF), S=mk(key+'S',d,colsS);
    const mF=toonMap(F.day), mS=toonMap(S.day), mT=mat(spec.roofColor||shade(spec.wall,0.25));
    const box=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),[mS,mS,mT,mT,mF,mF]); box.position.y=h/2; g.add(box); g.userData.facades={mF,mS,F,S};
    // 輪廓線（淡）
    const eg=new THREE.LineSegments(new THREE.EdgesGeometry(box.geometry),new THREE.LineBasicMaterial({color:0x3a2a1e,transparent:true,opacity:0.35})); eg.position.y=h/2; g.add(eg);
    if(spec.roof==='parapet'||!spec.roof){ const par=new THREE.Mesh(new THREE.BoxGeometry(w+0.3,0.5,d+0.3),mT); par.position.y=h+0.25; g.add(par); }
    if(spec.roof==='hip'){ const rh=spec.roofH||2.2; const shape=new THREE.Shape(); shape.moveTo(-w/2-0.8,0); shape.lineTo(w/2+0.8,0); shape.lineTo(w/2-1.2,rh); shape.lineTo(-w/2+1.2,rh); shape.closePath(); const geo=new THREE.ExtrudeGeometry(shape,{depth:d+1.6,bevelEnabled:false}); geo.translate(0,0,-(d+1.6)/2); const roof=new THREE.Mesh(geo,mat(spec.roofColor||'#7a4a3a')); roof.position.y=h; g.add(roof); const ridge=new THREE.Mesh(new THREE.BoxGeometry(w-2.2,0.25,0.5),mat(shade(spec.roofColor||'#7a4a3a',0.3))); ridge.position.y=h+rh+0.1; g.add(ridge); const tiles=canvasTex('tiles',128,128,(x,ww,hh)=>{ x.fillStyle=spec.roofColor||'#7a4a3a'; x.fillRect(0,0,ww,hh); x.strokeStyle='rgba(0,0,0,0.2)'; x.lineWidth=2; for(let j=0;j<hh;j+=16){ x.beginPath(); x.moveTo(0,j); x.lineTo(ww,j); x.stroke(); } for(let i=0;i<ww;i+=24){ x.beginPath(); x.moveTo(i,0); x.lineTo(i,hh); x.stroke(); } }); tiles.repeat.set(w/3,d/3); roof.material=toonMap(tiles); }
    // 入口
    const e=spec.entrance||{}; const ew=e.w||3.2, eh=e.h||3.0; const side=e.side||'front'; const ez= side==='front'? d/2 : -d/2; const dir= side==='front'?1:-1;
    const door=new THREE.Mesh(new THREE.BoxGeometry(ew,eh,0.3),mat('#3a3f46')); door.position.set(e.x||0,eh/2,ez+dir*0.02); g.add(door);
    const glassDoor=new THREE.Mesh(new THREE.PlaneGeometry(ew-0.3,eh-0.3),new THREE.MeshBasicMaterial({color:0xa9c9d6,transparent:true,opacity:0.7})); glassDoor.position.set(e.x||0,eh/2,ez+dir*0.2); if(dir<0) glassDoor.rotation.y=Math.PI; g.add(glassDoor);
    const frame=new THREE.Mesh(new THREE.BoxGeometry(ew+0.5,eh+0.4,0.25),mat(e.frame||shade(spec.wall,0.35))); frame.position.set(e.x||0,eh/2+0.1,ez+dir*0.1); g.add(frame); outline(frame,1.02);
    if(e.canopy!==false){ const cw=ew+2.4; const can=new THREE.Mesh(new THREE.BoxGeometry(cw,0.25,2.2),mat(e.canopyColor||shade(spec.wall,0.4))); can.position.set(e.x||0,eh+0.55,ez+dir*1.1); g.add(can); outline(can,1.02); for(const s of [-1,1]){ const col=new THREE.Mesh(new THREE.CylinderGeometry(0.12,0.12,eh+0.5,10),mat('#8f9399')); col.position.set((e.x||0)+s*(cw/2-0.4),(eh+0.5)/2,ez+dir*2.0); g.add(col); } }
    if(e.steps!==false){ for(let i=0;i<3;i++){ const st=new THREE.Mesh(new THREE.BoxGeometry(ew+3+i*0.8,0.14,0.55),mat(e.stepColor||'#cfc5b2')); st.position.set(e.x||0,0.07+(2-i)*0.14,ez+dir*(2.3+i*0.5)); g.add(st); } }
    if(spec.sign){ const sp=signPlane(spec.sign,Math.min(w*0.6,8),1.3,{color:spec.signColor||'#3b2a1e',bg:spec.signBg}); sp.position.set(e.x||0,spec.signY!==undefined?spec.signY:Math.min(eh+1.6,h-0.9),ez+dir*0.02); if(dir<0) sp.rotation.y=Math.PI; g.add(sp); }
    g.userData.footprint={w:w+0.2,d:d+0.2}; g.userData.entrance={x:e.x||0,z:ez+dir*3.2,side};
    return g; }
  function setNight(b,night){ const f=b.userData.facades; if(!f) return; f.mF.map=night?f.F.night:f.F.day; f.mS.map=night?f.S.night:f.S.day; f.mF.needsUpdate=true; f.mS.needsUpdate=true; }
  // ---- 樹 ----
  function leafTex(){ return canvasTex('leaf',128,256,(x,w,h)=>{ x.clearRect(0,0,w,h); x.fillStyle='#5f9a5e'; x.beginPath(); x.moveTo(64,0); x.quadraticCurveTo(120,90,64,256); x.quadraticCurveTo(8,90,64,0); x.fill(); x.strokeStyle='rgba(40,80,40,0.4)'; x.lineWidth=3; x.beginPath(); x.moveTo(64,10); x.lineTo(64,246); x.stroke(); for(let i=0;i<10;i++){ x.beginPath(); x.moveTo(64,30+i*20); x.lineTo(20,45+i*20); x.moveTo(64,30+i*20); x.lineTo(108,45+i*20); x.stroke(); } }); }
  // ---- 風：以 vertex shader 讓葉子輕微擺動（合併後仍有效）----
  const windMats=[]; function windify(m,amt){ m.onBeforeCompile=sh=>{ sh.uniforms.uTime={value:0}; sh.vertexShader='uniform float uTime;\n'+sh.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n{ vec4 wp4=modelMatrix*vec4(position,1.0); float sw='+amt+'; transformed.x+=sin(uTime*1.3+wp4.x*0.35+wp4.z*0.2+wp4.y*0.5)*sw; transformed.z+=cos(uTime*1.1+wp4.z*0.3+wp4.y*0.4)*sw*0.6; transformed.y-=abs(sin(uTime*0.7+wp4.x*0.2))*sw*0.35; }'); m.userData.shader=sh; }; m.customProgramCacheKey=()=>'wind'+amt; windMats.push(m); return m; }
  function updateWind(t){ for(const m of windMats){ if(m.userData.shader) m.userData.shader.uniforms.uTime.value=t; } }
  let palmLeafMat=null; function getPalmLeafMat(){ if(!palmLeafMat){ palmLeafMat=windify(new THREE.MeshStandardMaterial({map:leafTex(),transparent:true,alphaTest:0.5,side:THREE.DoubleSide,roughness:0.9}),'(0.08*uv.y*uv.y)'); } return palmLeafMat; }
  const folCache={}; function foliageMat(c){ if(!folCache[c]) folCache[c]=windify(new THREE.MeshStandardMaterial({color:new THREE.Color(c),roughness:0.95,metalness:0}),'0.035'); return folCache[c]; }
  function palm(h){ h=h||8; const g=new THREE.Group(); const trunkT=canvasTex('palmtrunk',64,256,(x,w,hh)=>{ x.fillStyle='#9c8466'; x.fillRect(0,0,w,hh); for(let j=0;j<hh;j+=14){ x.fillStyle=j%28?'#8a7256':'#a89070'; x.fillRect(0,j,w,7); } }); trunkT.repeat.set(1,h/2); const trunk=new THREE.Mesh(new THREE.CylinderGeometry(0.16,0.28,h,10),toonMap(trunkT)); trunk.position.y=h/2; g.add(trunk); const crown=new THREE.Group(); crown.position.y=h; g.add(crown); const lm=getPalmLeafMat(); const n=9; for(let i=0;i<n;i++){ const leaf=new THREE.Mesh(G('palmLeaf',()=>{ const p=new THREE.PlaneGeometry(1.1,3.6,1,6); p.translate(0,1.7,0); const pos=p.attributes.position; for(let k=0;k<pos.count;k++){ const y=pos.getY(k); pos.setZ(k,-Math.pow(y/3.6,2)*1.6); } p.computeVertexNormals(); return p; }),lm); leaf.rotation.y=i/n*Math.PI*2; leaf.rotation.x=-Math.PI/2+0.35; leaf.rotation.order='YXZ'; leaf.userData.base=leaf.rotation.x; crown.add(leaf); } const core=new THREE.Mesh(new THREE.SphereGeometry(0.4,8,6),mat('#6f8f4f')); crown.add(core); g.userData={kind:'palm',crown,radius:0.35}; return g; }
  function banyan(scale){ scale=scale||1; const g=new THREE.Group(); const trunk=new THREE.Mesh(new THREE.CylinderGeometry(0.35*scale,0.6*scale,2.6*scale,10),mat('#6f5a48')); trunk.position.y=1.3*scale; g.add(trunk); outline(trunk,1.03); for(let i=0;i<4;i++){ const a=i/4*Math.PI*2+0.4; const root=new THREE.Mesh(new THREE.CylinderGeometry(0.05,0.12,2.2*scale,6),mat('#7c6552')); root.position.set(Math.cos(a)*0.9*scale,1.1*scale,Math.sin(a)*0.9*scale); root.rotation.z=Math.cos(a)*0.25; root.rotation.x=-Math.sin(a)*0.25; g.add(root); } const cols=['#4e8c57','#5f9a5e','#74ab6c','#8cc08a']; const blobs=[[0,3.6,0,2.2],[1.6,3.2,0.6,1.5],[-1.5,3.3,0.4,1.6],[0.4,3.1,-1.6,1.5],[-0.3,3.2,1.6,1.4],[0.9,4.4,-0.4,1.3],[-1,4.3,-0.6,1.2]]; for(let i=0;i<blobs.length;i++){ const b=blobs[i]; const m=new THREE.Mesh(G('blob'+i,()=>{ const s=new THREE.SphereGeometry(1,10,8); const p=s.attributes.position; for(let k=0;k<p.count;k++){ const vx=p.getX(k),vy=p.getY(k),vz=p.getZ(k); const n=1+0.12*Math.sin(vx*5+i)*Math.cos(vz*4-i)+0.08*Math.sin(vy*6); p.setXYZ(k,vx*n,vy*n*0.85,vz*n); } s.computeVertexNormals(); return s; }),foliageMat(cols[i%cols.length])); m.position.set(b[0]*scale,b[1]*scale,b[2]*scale); m.scale.setScalar(b[3]*scale); g.add(m); outline(m,1.03); } g.userData={kind:'banyan',radius:0.7*scale}; return g; }
  function bush(r){ r=r||0.6; const g=new THREE.Group(); for(let i=0;i<3;i++){ const m=new THREE.Mesh(G('bush',()=>new THREE.SphereGeometry(1,9,7)),foliageMat(i===1?'#6faa6c':'#5f9a5e')); m.position.set((i-1)*r*0.7,r*0.7,(i%2)*r*0.3); m.scale.set(r,r*0.8,r); g.add(m); outline(m,1.04); } return g; }
  function hedge(len){ const m=new THREE.Mesh(new THREE.BoxGeometry(len,0.7,0.7,Math.max(2,len|0),1,1),mat('#5f9a5e')); m.position.y=0.35; outline(m,1.02); return m; }
  // ---- 道具 ----
  function bench(){ const g=new THREE.Group(); const wood=mat('#a8744a'); for(let i=0;i<3;i++){ const p=new THREE.Mesh(new THREE.BoxGeometry(1.8,0.06,0.16),wood); p.position.set(0,0.45,-0.2+i*0.2); g.add(p); outline(p,1.03); } for(let i=0;i<2;i++){ const p=new THREE.Mesh(new THREE.BoxGeometry(1.8,0.16,0.06),wood); p.position.set(0,0.62+i*0.2,-0.3); g.add(p); } for(const s of [-1,1]){ const leg=new THREE.Mesh(new THREE.BoxGeometry(0.08,0.45,0.5),mat('#3a3f46')); leg.position.set(s*0.75,0.22,0); g.add(leg); const back=new THREE.Mesh(new THREE.BoxGeometry(0.08,0.5,0.08),mat('#3a3f46')); back.position.set(s*0.75,0.7,-0.3); g.add(back); } g.userData={seat:{y:0.45}}; return g; }
  function lampPost(){ const g=new THREE.Group(); const pole=new THREE.Mesh(new THREE.CylinderGeometry(0.06,0.08,4.2,8),mat('#3a3f46')); pole.position.y=2.1; g.add(pole); const arm=new THREE.Mesh(new THREE.BoxGeometry(0.08,0.08,0.9),mat('#3a3f46')); arm.position.set(0,4.1,0.4); g.add(arm); const head=new THREE.Mesh(new THREE.BoxGeometry(0.4,0.18,0.6),mat('#4a5058')); head.position.set(0,4.05,0.75); g.add(head); const bulb=new THREE.Mesh(new THREE.BoxGeometry(0.34,0.04,0.5),new THREE.MeshBasicMaterial({color:0xfff2c8})); bulb.position.set(0,3.95,0.75); g.add(bulb); g.userData={lamp:bulb,lightPos:new THREE.Vector3(0,3.9,0.75)}; return g; }
  function bike(color){ const g=new THREE.Group(); const dark=new THREE.MeshBasicMaterial({color:0x2b2b2b}); const fm=mat(color||'#3a6fb0'); for(const s of [-1,1]){ const wheel=new THREE.Mesh(G('wheel',()=>new THREE.TorusGeometry(0.3,0.035,6,18)),dark); wheel.position.set(0,0.3,s*0.45); g.add(wheel); const hub=new THREE.Mesh(G('hub',()=>new THREE.CircleGeometry(0.28,12)),new THREE.MeshBasicMaterial({color:0x777777,transparent:true,opacity:0.35,side:THREE.DoubleSide})); hub.position.copy(wheel.position); g.add(hub); } const tube=(a,b)=>{ const dir=new THREE.Vector3().subVectors(b,a); const len=dir.length(); const m=new THREE.Mesh(new THREE.CylinderGeometry(0.025,0.025,len,6),fm); m.position.copy(a).add(dir.multiplyScalar(0.5)); m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize()); g.add(m); }; const P=(x,y,z)=>new THREE.Vector3(x,y,z); tube(P(0,0.3,-0.45),P(0,0.72,-0.15)); tube(P(0,0.72,-0.15),P(0,0.42,0.1)); tube(P(0,0.42,0.1),P(0,0.3,0.45)); tube(P(0,0.72,-0.15),P(0,0.75,0.3)); tube(P(0,0.75,0.3),P(0,0.3,0.45)); tube(P(0,0.42,0.1),P(0,0.72,-0.15)); const seat=new THREE.Mesh(new THREE.BoxGeometry(0.1,0.05,0.22),dark); seat.position.set(0,0.82,-0.12); g.add(seat); const bar=new THREE.Mesh(new THREE.BoxGeometry(0.4,0.03,0.03),dark); bar.position.set(0,0.84,0.32); g.add(bar); g.rotation.y=Math.PI/2; return g; }
  function bikeRack(n,color){ const g=new THREE.Group(); const rail=new THREE.Mesh(new THREE.BoxGeometry(n*0.6+0.4,0.05,0.05),mat('#8f9399')); rail.position.set(0,0.45,-0.5); g.add(rail); const cols=['#3a6fb0','#8c3b47','#2f5d50','#e0b95b','#7b6a5a','#c46a4a']; for(let i=0;i<n;i++){ if(Math.random()<0.3) continue; const b=bike(color||cols[i%cols.length]); b.position.set((i-(n-1)/2)*0.6,0,0); g.add(b); } return g; }
  function bulletin(){ const g=new THREE.Group(); for(const s of [-1,1]){ const post=new THREE.Mesh(new THREE.BoxGeometry(0.12,2.4,0.12),mat('#5c3a21')); post.position.set(s*1.1,1.2,0); g.add(post); } const board=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.5,0.08),mat('#8b5e3c')); board.position.set(0,1.65,0); g.add(board); outline(board,1.02); const cork=new THREE.Mesh(new THREE.PlaneGeometry(2.2,1.3),mat('#c9a57a')); cork.position.set(0,1.65,0.05); g.add(cork); const cols=['#f6dfa8','#ffffff','#cfe3ea','#f4b8a8','#d7e3ce']; for(let i=0;i<7;i++){ const p=new THREE.Mesh(new THREE.PlaneGeometry(0.42,0.55),new THREE.MeshBasicMaterial({color:cols[i%cols.length]})); p.position.set(-0.85+(i%4)*0.55+(i>3?0.25:0),1.85-(i>3?0.5:0)+ (Math.random()*0.06),0.06); p.rotation.z=(Math.random()-0.5)*0.12; g.add(p); } const roof=new THREE.Mesh(new THREE.BoxGeometry(2.6,0.08,0.5),mat('#5c3a21')); roof.position.set(0,2.45,0.1); g.add(roof); g.userData={cork}; return g; }
  function planter(){ const g=new THREE.Group(); const box=new THREE.Mesh(new THREE.BoxGeometry(1.2,0.5,0.5),mat('#9a8a7a')); box.position.y=0.25; g.add(box); outline(box,1.02); const flowers=['#e07a7a','#f2c14e','#f7f7f4','#c46a9a']; for(let i=0;i<6;i++){ const f=new THREE.Mesh(G('flower',()=>new THREE.SphereGeometry(0.09,7,5)),mat(flowers[i%4])); f.position.set(-0.45+i*0.18,0.62,(i%2?0.12:-0.12)); g.add(f); } const green=new THREE.Mesh(new THREE.BoxGeometry(1.1,0.16,0.4),mat('#5f9a5e')); green.position.y=0.55; g.add(green); return g; }
  function bell(){ // 傅鐘風格：小鐘亭
    const g=new THREE.Group(); const base=new THREE.Mesh(new THREE.CylinderGeometry(1.4,1.6,0.5,12),mat('#cfc5b2')); base.position.y=0.25; g.add(base); for(let i=0;i<4;i++){ const a=i/4*Math.PI*2+Math.PI/4; const col=new THREE.Mesh(new THREE.CylinderGeometry(0.12,0.12,3.4,8),mat('#e8dcc4')); col.position.set(Math.cos(a)*0.9,2.2,Math.sin(a)*0.9); g.add(col); } const top=new THREE.Mesh(new THREE.ConeGeometry(1.5,0.9,4),mat('#6e8f79')); top.rotation.y=Math.PI/4; top.position.y=4.3; g.add(top); const bellM=new THREE.Mesh(G('bell',()=>P3.lathe([[0.001,0],[0.45,0],[0.42,0.25],[0.3,0.75],[0.001,0.85]],14)),mat('#5d5a4a')); bellM.position.y=2.6; g.add(bellM); outline(bellM,1.04); return g; }
  function vending(){ const g=new THREE.Group(); const box=new THREE.Mesh(new THREE.BoxGeometry(1.1,1.9,0.8),mat('#c94a4a')); box.position.y=0.95; g.add(box); outline(box,1.02); const glass=new THREE.Mesh(new THREE.PlaneGeometry(0.6,1.1),new THREE.MeshBasicMaterial({color:0xbcd6df})); glass.position.set(-0.15,1.2,0.41); g.add(glass); const panel=new THREE.Mesh(new THREE.PlaneGeometry(0.3,1.1),new THREE.MeshBasicMaterial({color:0x2b2b2b})); panel.position.set(0.33,1.2,0.41); g.add(panel); return g; }
  function scooter(color){ const g=new THREE.Group(); const body=new THREE.Mesh(new THREE.BoxGeometry(0.5,0.4,1.4),mat(color||'#e8e8e8')); body.position.set(0,0.5,0); g.add(body); outline(body,1.02); for(const s of [-1,1]){ const w=new THREE.Mesh(G('swheel',()=>new THREE.TorusGeometry(0.22,0.07,6,14)),new THREE.MeshBasicMaterial({color:0x2b2b2b})); w.position.set(0,0.22,s*0.6); g.add(w); } const seat=new THREE.Mesh(new THREE.BoxGeometry(0.4,0.12,0.6),mat('#3a3f46')); seat.position.set(0,0.75,-0.2); g.add(seat); const bar=new THREE.Mesh(new THREE.BoxGeometry(0.5,0.04,0.04),mat('#3a3f46')); bar.position.set(0,0.95,0.55); g.add(bar); return g; }
  function foodCart(name){ const g=new THREE.Group(); const cart=new THREE.Mesh(new THREE.BoxGeometry(2.2,1.1,1.0),mat('#c9c3b8')); cart.position.y=0.75; g.add(cart); outline(cart,1.02); const roof=new THREE.Mesh(new THREE.BoxGeometry(2.6,0.1,1.6),mat('#8c3b47')); roof.position.y=2.2; g.add(roof); for(const s of [-1,1]){ const p=new THREE.Mesh(new THREE.CylinderGeometry(0.04,0.04,1.1,6),mat('#8f9399')); p.position.set(s*1.0,1.65,0.4); g.add(p); } const lamp=new THREE.Mesh(new THREE.SphereGeometry(0.12,8,6),new THREE.MeshBasicMaterial({color:0xffe08a})); lamp.position.set(0,1.95,0.5); g.add(lamp); const sp=signPlane(name||'鹹酥雞',2,0.6,{color:'#ffffff'}); sp.position.set(0,2.0,0.82); g.add(sp); for(const s of [-1,1]){ const w=new THREE.Mesh(G('cwheel',()=>new THREE.TorusGeometry(0.2,0.05,6,12)),new THREE.MeshBasicMaterial({color:0x2b2b2b})); w.position.set(s*0.8,0.2,0.45); w.rotation.y=Math.PI/2; g.add(w); } g.userData={lamp}; return g; }
  function gate(){ // 校門：紅磚門柱與拱
    const g=new THREE.Group(); const bm=toonMap(brickTex('#b8735a')); for(const s of [-1,1]){ const pil=new THREE.Mesh(new THREE.BoxGeometry(1.6,4.2,1.6),bm); pil.position.set(s*5,2.1,0); g.add(pil); outline(pil,1.01); const cap=new THREE.Mesh(new THREE.BoxGeometry(2.0,0.3,2.0),mat('#cfc5b2')); cap.position.set(s*5,4.35,0); g.add(cap); } for(const s of [-1,1]){ const wall=new THREE.Mesh(new THREE.BoxGeometry(3.5,1.6,0.8),bm); wall.position.set(s*8.5,0.8,0); g.add(wall); } const sp=signPlane('國立臺灣大學',6,1,{color:'#3b2a1e'}); sp.position.set(0,3.4,0.02); const board=new THREE.Mesh(new THREE.BoxGeometry(6.4,1.2,0.2),mat('#f4ead8')); board.position.set(0,3.4,-0.1); g.add(board); g.add(sp);
    // 警衛室：紅磚小屋、斜屋頂、小窗
    { const h=new THREE.Group(); const body=new THREE.Mesh(new THREE.BoxGeometry(4.2,3.0,3.4),bm); body.position.y=1.5; h.add(body); const roof=new THREE.Mesh(new THREE.ConeGeometry(3.4,1.4,4),mat('#5c3a2a')); roof.rotation.y=Math.PI/4; roof.position.y=3.7; roof.scale.set(1,1,0.85); h.add(roof); for(const [x,z,ry] of [[0,1.71,0],[2.11,0,Math.PI/2]]){ const win=new THREE.Mesh(new THREE.PlaneGeometry(1.4,0.9),new THREE.MeshStandardMaterial({color:0xbcd6df,roughness:0.3})); win.position.set(x,1.7,z); win.rotation.y=ry; h.add(win); } const door=new THREE.Mesh(new THREE.PlaneGeometry(0.9,2.0),mat('#3b2a1e')); door.position.set(-1.2,1.0,1.71); h.add(door); h.position.set(-13.5,0,0.9); g.add(h); g.userData.gatehouse={x:-13.5,z:0.9,w:4.4,d:3.6}; }
    return g; }
  function mrtEntrance(name){ const g=new THREE.Group(); const roof=new THREE.Mesh(new THREE.BoxGeometry(3.2,0.15,2.6),mat('#4a5058')); roof.position.y=2.6; g.add(roof); for(const [x,z] of [[-1.5,-1.2],[1.5,-1.2],[-1.5,1.2],[1.5,1.2]]){ const p=new THREE.Mesh(new THREE.CylinderGeometry(0.06,0.06,2.6,8),mat('#8f9399')); p.position.set(x,1.3,z); g.add(p); } const stairs=new THREE.Mesh(new THREE.BoxGeometry(2.6,0.1,2.2),mat('#3a3f46')); stairs.position.y=0.05; g.add(stairs); const rail=new THREE.Mesh(new THREE.BoxGeometry(2.8,0.9,0.05),mat('#8f9399')); rail.position.set(0,0.5,-1.15); g.add(rail); const sign=new THREE.Mesh(new THREE.BoxGeometry(2.6,0.6,0.15),mat('#2f5d50')); sign.position.set(0,3.1,0); g.add(sign); const sp=signPlane(name||'捷運 公館站',2.4,0.5,{color:'#ffffff'}); sp.position.set(0,3.1,0.09); g.add(sp); return g; }
  function awning(w,color){ const g=new THREE.Group(); const m=new THREE.Mesh(new THREE.BoxGeometry(w,0.08,1.2),mat(color||'#8c3b47')); m.position.set(0,0,0.6); m.rotation.x=0.25; g.add(m); const tex=canvasTex('awn'+color,128,32,(x,ww,hh)=>{ x.fillStyle=color||'#8c3b47'; x.fillRect(0,0,ww,hh); x.fillStyle='rgba(255,255,255,0.7)'; for(let i=0;i<ww;i+=32) x.fillRect(i,0,16,hh); }); tex.repeat.set(w/1.2,1); m.material=toonMap(tex); return g; }
  return {canvasTex,grassTex,pathTex,asphaltTex,brickTex,stoneTex,facadeTex,signPlane,signTex,building,setNight,palm,banyan,bush,hedge,bench,lampPost,bike,bikeRack,bulletin,planter,bell,vending,scooter,foodCart,gate,mrtEntrance,awning,updateWind,foliageMat};
})();
